package cn.com.wito.auth.po;

import java.util.Date;

/**
 * 门店实体
 * 
 * @author wujia<1438019595@qq.com>
 * 
 */
public class Store extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4830894164188144671L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.code
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.name
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.address
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.latitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String latitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.longitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String longitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.sent_price
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String sentPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.business_time
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String businessTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.sent_scope
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String sentScope;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String subjectCode;

	/**
	 * 主体名称
	 */
	private String subjectName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_store.remark
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.remark
	 * 
	 * @return the value of t_store.remark
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.remark
	 * 
	 * @param remark
	 *            the value for t_store.remark
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.code
	 * 
	 * @return the value of t_store.code
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.code
	 * 
	 * @param code
	 *            the value for t_store.code
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.name
	 * 
	 * @return the value of t_store.name
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.name
	 * 
	 * @param name
	 *            the value for t_store.name
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.address
	 * 
	 * @return the value of t_store.address
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.address
	 * 
	 * @param address
	 *            the value for t_store.address
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.latitude
	 * 
	 * @return the value of t_store.latitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.latitude
	 * 
	 * @param latitude
	 *            the value for t_store.latitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude == null ? null : latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.longitude
	 * 
	 * @return the value of t_store.longitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.longitude
	 * 
	 * @param longitude
	 *            the value for t_store.longitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude == null ? null : longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.sent_price
	 * 
	 * @return the value of t_store.sent_price
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getSentPrice() {
		return sentPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.sent_price
	 * 
	 * @param sentPrice
	 *            the value for t_store.sent_price
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setSentPrice(String sentPrice) {
		this.sentPrice = sentPrice == null ? null : sentPrice.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.business_time
	 * 
	 * @return the value of t_store.business_time
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getBusinessTime() {
		return businessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.business_time
	 * 
	 * @param businessTime
	 *            the value for t_store.business_time
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setBusinessTime(String businessTime) {
		this.businessTime = businessTime == null ? null : businessTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.sent_scope
	 * 
	 * @return the value of t_store.sent_scope
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getSentScope() {
		return sentScope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.sent_scope
	 * 
	 * @param sentScope
	 *            the value for t_store.sent_scope
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setSentScope(String sentScope) {
		this.sentScope = sentScope == null ? null : sentScope.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_store.sub_id
	 * 
	 * @return the value of t_store.sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getSubjectCode() {
		return subjectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_store.sub_id
	 * 
	 * @param subId
	 *            the value for t_store.sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Store() {
		super();
	}

	public Store(Integer enableFlag, String createBy, Date createDate,
			String updateBy, Date updateDate, String code, String name,
			String address, String latitude, String longitude,
			String sentPrice, String businessTime, String sentScope,
			String subjectCode, String subjectName, String remark) {
		super(null, enableFlag, createBy, createDate, updateBy, updateDate);
		this.code = code;
		this.name = name;
		this.address = address;
		this.latitude = latitude;
		this.longitude = longitude;
		this.sentPrice = sentPrice;
		this.businessTime = businessTime;
		this.sentScope = sentScope;
		this.subjectCode = subjectCode;
		this.subjectName = subjectName;
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "Store [code=" + code + ", name=" + name + ", address="
				+ address + ", latitude=" + latitude + ", longitude="
				+ longitude + ", sentPrice=" + sentPrice + ", businessTime="
				+ businessTime + ", sentScope=" + sentScope + ", subjectCode="
				+ subjectCode + ", remark=" + remark + "]";
	}

}