package cn.com.wito.auth.po;

import java.util.Date;

/**
 * 售货机实体
 * 
 * @author wujia<1438019595@qq.com>
 * 
 */
public class VendingMachine extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2121157097648241786L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.remark
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.code
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.ser_num
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String serNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.name
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.latitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String latitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.longitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String longitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.address
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String address;
	private Integer statas;

	/**
	 * 商铺编号
	 * 
	 */
	private String storeCode;
	
	/**
	 * 商铺名称
	 * 
	 */
	private String storeName;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.delivery_sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String deliverySubjectCode;

	private String deliverySubjectName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_machine.operate_sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	private String operateSubjectCode;

	private String operateSubjectName;

	public String getStoreCode() {
		return storeCode;
	}

	public void setStoreCode(String storeCode) {
		this.storeCode = storeCode;
	}

	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public Integer getStatas() {
		return statas;
	}

	public void setStatas(Integer statas) {
		this.statas = statas;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public VendingMachine() {

	}

	public VendingMachine(Integer enableFlag,Integer statas, String createBy, Date createDate,
			String updateBy, Date updateDate, String remark, String code,
			String serNum, String name, String latitude, String longitude,
			String address,String storeCode,String storeName, String deliverySubjectCode,
			String deliverySubjectName, String operateSubjectCode,
			String operateSubjectName) {
		super(null, enableFlag, createBy, createDate, updateBy, updateDate);
		this.statas=statas;
		this.remark = remark;
		this.code = code;
		this.serNum = serNum;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.address = address;
		this.storeCode = storeCode;
		this.storeName = storeName;
		this.deliverySubjectCode = deliverySubjectCode;
		this.deliverySubjectName = deliverySubjectName;
		this.operateSubjectCode = operateSubjectCode;
		this.operateSubjectName = operateSubjectName;
		this.statas=statas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.remark
	 * 
	 * @return the value of t_machine.remark
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.remark
	 * 
	 * @param remark
	 *            the value for t_machine.remark
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.code
	 * 
	 * @return the value of t_machine.code
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.code
	 * 
	 * @param code
	 *            the value for t_machine.code
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.ser_num
	 * 
	 * @return the value of t_machine.ser_num
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getSerNum() {
		return serNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.ser_num
	 * 
	 * @param serNum
	 *            the value for t_machine.ser_num
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setSerNum(String serNum) {
		this.serNum = serNum == null ? null : serNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.name
	 * 
	 * @return the value of t_machine.name
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.name
	 * 
	 * @param name
	 *            the value for t_machine.name
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.latitude
	 * 
	 * @return the value of t_machine.latitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.latitude
	 * 
	 * @param latitude
	 *            the value for t_machine.latitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setLatitude(String latitude) {
		this.latitude = latitude == null ? null : latitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.longitude
	 * 
	 * @return the value of t_machine.longitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.longitude
	 * 
	 * @param longitude
	 *            the value for t_machine.longitude
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setLongitude(String longitude) {
		this.longitude = longitude == null ? null : longitude.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.address
	 * 
	 * @return the value of t_machine.address
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.address
	 * 
	 * @param address
	 *            the value for t_machine.address
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.delivery_sub_id
	 * 
	 * @return the value of t_machine.delivery_sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getDeliverySubjectCode() {
		return deliverySubjectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.delivery_sub_id
	 * 
	 * @param deliverySubId
	 *            the value for t_machine.delivery_sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setDeliverySubjectCode(String deliverySubjectCode) {
		this.deliverySubjectCode = deliverySubjectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_machine.operate_sub_id
	 * 
	 * @return the value of t_machine.operate_sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public String getOperateSubjectCode() {
		return operateSubjectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_machine.operate_sub_id
	 * 
	 * @param operateSubId
	 *            the value for t_machine.operate_sub_id
	 * 
	 * @mbggenerated Sun Aug 23 13:22:43 CST 2015
	 */
	public void setOperateSubjectCode(String operateSubjectCode) {
		this.operateSubjectCode = operateSubjectCode;
	}

	public String getDeliverySubjectName() {
		return deliverySubjectName;
	}

	public void setDeliverySubjectName(String deliverySubjectName) {
		this.deliverySubjectName = deliverySubjectName;
	}

	public String getOperateSubjectName() {
		return operateSubjectName;
	}

	public void setOperateSubjectName(String operateSubjectName) {
		this.operateSubjectName = operateSubjectName;
	}

	@Override
	public String toString() {
		return "VendingMachine [remark=" + remark + ",statas="+statas+", code=" + code
				+ ", serNum=" + serNum + ", name=" + name + ", latitude="
				+ latitude + ", longitude=" + longitude + ", address="
				+ address + ", deliverySubjectCode=" + deliverySubjectCode
				+ ", deliverySubjectName=" + deliverySubjectName
				+ ", operateSubjectCode=" + operateSubjectCode
				+ ", operateSubjectName=" + operateSubjectName + "]";
	}

}